# Generated by Django 5.2 on 2025-04-08 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=2048, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, max_length=256, null=True, verbose_name='URL изображения')),
                ('category', models.CharField(max_length=128, verbose_name='Категория')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у'), ('refurbished', 'Восстановленный')], max_length=25, verbose_name='Состояние')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('comment', models.CharField(max_length=2048, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('awaiting', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='awaiting', max_length=25, verbose_name='Статус')),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_as_receiver', to='ads.ad', verbose_name='Объявление-получатель')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_as_sender', to='ads.ad', verbose_name='Объявление-инициатор')),
            ],
            options={
                'verbose_name': 'Предложение об обмене',
                'verbose_name_plural': 'Предложения об обмене',
            },
        ),
    ]
